services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_api
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: