"""Añade soft delete a Company

Revision ID: 24e8334dad0d
Revises: 08fbf564e947
Create Date: 2025-09-04 00:18:01.291759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e8334dad0d'
down_revision: Union[str, Sequence[str], None] = '08fbf564e947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'deleted_at')
    # ### end Alembic commands ###
